# -*- coding: utf-8 -*-
"""DecisionTree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iL7UgX0Q84g9ptpgKEOE1dfE98ttUyZj

Source: https://towardsdatascience.com/visualizing-decision-trees-in-jupyter-notebook-with-python-and-graphviz-78703230a7b1

## Decision Tree of Sepal

# Inisialisasi library & Dataset
"""

import pandas as pd
import numpy as np
from sklearn import datasets

FEATURE_NAMES = ['Sepal Length', 'Sepal Width', 'Petal Length', 'Petal Width']

iris = datasets.load_iris()
X = pd.DataFrame(iris.data, columns = FEATURE_NAMES)
y = iris.target

"""# Fitting Dataset"""

from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X,y)

"""# Export result menjadi .dot"""

from sklearn.tree import export_graphviz
export_graphviz(model, 'tree.dot', feature_names = FEATURE_NAMES)

"""# Reformat output dari .dot menjadi .png"""

! dot -Tpng tree.dot -o tree.png

"""# Buat visualisasi"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import cv2
# %matplotlib inline
img = cv2.imread('tree.png')
plt.figure(figsize = (20, 20))
plt.imshow(img)